name = "ConcreteDropout"
uuid = "cefad46e-21aa-447d-abc5-91039c0799ef"
authors = ["David MÃ©tivier <david.metivier@inrae.fr> and contributors"]
version = "0.0.0"

[deps]
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"

[compat]
julia = "1"
